server {
  listen 80;
  client_max_body_size 20m;
  location / {
    proxy_pass http://frontend:18080;
    proxy_set_header Host $host;
  }
  location /api/ {
    proxy_pass http://backend:18081/api/;
    proxy_set_header Host $host;
  }
}
